from __future__ import annotations

import time
import pandas as pd
import streamlit as st

from agent import check_slide_claim, DEFAULT_MODEL
from export import build_report, EXPORT_BUILD
from pptx_ingest import extract_deck

EXPECTED_EXPORT_BUILD = "2026.08.02.2"
if EXPORT_BUILD != EXPECTED_EXPORT_BUILD:
    st.error(
        "The app files are from different packages. Replace both app.py and export.py "
        "with the files from the same hotfix ZIP, commit them together, and reboot the app."
    )
    st.stop()

st.set_page_config(page_title="Slide QA Copilot", page_icon="🖥️", layout="wide")
st.title("🖥️ Slide QA Copilot")
st.caption("Source-based review of slide claims and their cited evidence.")
st.caption("Internal beta · Analyst review required.")

with st.sidebar:
    st.header("⚙️ Settings")
    api_key = st.text_input("Gemini API Key", type="password")
    model = st.selectbox("Gemini model", ["gemini-3.5-flash", "gemini-2.5-flash"], index=0)
    project_context = st.text_area(
        "Optional project context",
        placeholder="Example: Industrial micronized powders. Metallic materials are out of scope. Require direct evidence for company capabilities and market claims.",
        height=150,
    )
    qa_instruction = st.text_area(
        "Optional QA instruction",
        placeholder="Example: Be strict with inference. Check numbers, denominators, geography, commercial status, and whether the slide wording is stronger than the cited evidence.",
        height=150,
    )
    st.divider()
    st.info(
        "Data note: use only project content approved for external processing. "
        "Where practical, remove client names and unnecessary confidential identifiers before upload."
    )
    st.caption("The browser tab must remain open while the QA run is processing.")

uploaded = st.file_uploader(
    "Upload a PowerPoint (.pptx) or the CSV generated by the optional Google Slides extractor",
    type=["pptx", "csv"],
)
if not uploaded:
    st.info("Start with a small test deck. PPTX is the recommended format for the first prototype.")
    st.stop()

try:
    data = uploaded.getvalue()
    claims_df = extract_deck(data, uploaded.name)
except Exception as exc:
    st.error(f"Could not read the deck: {exc}")
    st.stop()

if claims_df.empty:
    st.warning("No paragraphs with usable hyperlinks were found. Check whether the references are true hyperlinks, not only blue text.")
    st.stop()

st.success(
    f"Detected **{len(claims_df)} referenced claim(s)** across "
    f"**{claims_df['slide_number'].nunique()} slide(s)**, with **{claims_df['url_count'].sum()} reference occurrence(s)**."
)

unique_urls = {
    url.strip()
    for raw in claims_df["urls"].astype(str)
    for url in raw.split(" | ")
    if url.strip()
}
summary_cols = st.columns(5)
summary_cols[0].metric("Referenced claims", len(claims_df))
summary_cols[1].metric("Slides with references", claims_df["slide_number"].nunique())
summary_cols[2].metric("Reference occurrences", int(claims_df["url_count"].sum()))
summary_cols[3].metric("Unique URLs", len(unique_urls))
summary_cols[4].metric("Multi-source claims", int((claims_df["url_count"] > 1).sum()))

mapping_issues = claims_df[claims_df["mapping_note"].str.contains("Incomplete|unclear|Shape-level", case=False, na=False)]
if len(mapping_issues):
    st.warning(f"{len(mapping_issues)} claim(s) have unclear or incomplete claim-to-reference mapping. Review these before running.")

st.subheader("1. Review and select extracted claims")
st.caption("Use the filters for large decks. Each selected claim currently makes one Gemini request.")

min_slide = int(claims_df["slide_number"].min())
max_slide = int(claims_df["slide_number"].max())
filter_cols = st.columns([1, 1, 1.3])
with filter_cols[0]:
    slide_from = st.number_input("From slide", min_value=min_slide, max_value=max_slide, value=min_slide)
with filter_cols[1]:
    slide_to = st.number_input("To slide", min_value=min_slide, max_value=max_slide, value=max_slide)
with filter_cols[2]:
    search_text = st.text_input("Search title or claim", placeholder="Optional keyword")

option_cols = st.columns(3)
with option_cols[0]:
    multi_only = st.checkbox("Only claims with multiple references", value=False)
with option_cols[1]:
    mapping_only = st.checkbox("Only mapping issues", value=False)
with option_cols[2]:
    select_all_filtered = st.checkbox("Select all filtered claims", value=False)

filtered_claims = claims_df[
    claims_df["slide_number"].between(int(slide_from), int(slide_to))
].copy()
if search_text.strip():
    needle = search_text.strip().lower()
    filtered_claims = filtered_claims[
        filtered_claims["slide_title"].astype(str).str.lower().str.contains(needle, regex=False)
        | filtered_claims["clean_claim"].astype(str).str.lower().str.contains(needle, regex=False)
    ]
if multi_only:
    filtered_claims = filtered_claims[filtered_claims["url_count"] > 1]
if mapping_only:
    filtered_claims = filtered_claims[
        filtered_claims["mapping_note"].str.contains("Incomplete|unclear|Shape-level", case=False, na=False)
    ]

st.caption(f"Showing **{len(filtered_claims)}** of **{len(claims_df)}** referenced claims.")
preview = filtered_claims[[
    "claim_id", "slide_number", "slide_title", "clean_claim",
    "url_count", "mapping_note",
]].copy()
preview.insert(0, "Run", bool(select_all_filtered))

edited = st.data_editor(
    preview,
    hide_index=True,
    use_container_width=True,
    height=520,
    column_config={
        "Run": st.column_config.CheckboxColumn("Run", required=True, width="small"),
        "claim_id": st.column_config.TextColumn("ID", width="small"),
        "slide_number": st.column_config.NumberColumn("Slide", width="small"),
        "slide_title": st.column_config.TextColumn("Slide title", width="medium"),
        "clean_claim": st.column_config.TextColumn("Claim", width="large"),
        "url_count": st.column_config.NumberColumn("Refs", width="small"),
        "mapping_note": st.column_config.TextColumn("Reference mapping", width="medium"),
    },
    disabled=[c for c in preview.columns if c != "Run"],
    key="claim_selection_editor",
)
selected_ids = edited.loc[edited["Run"], "claim_id"].tolist()
selected = claims_df[claims_df["claim_id"].isin(selected_ids)].copy()

st.subheader("2. Confirm and run")
st.write(f"Selected claims: **{len(selected)}**")
confirm = st.checkbox("I reviewed the extracted claim text and reference counts.")

if "slide_results" not in st.session_state:
    st.session_state.slide_results = []

c1, c2 = st.columns(2)
with c1:
    run = st.button("🚀 Run Slide QA", type="primary", use_container_width=True, disabled=not (confirm and len(selected) and api_key))
with c2:
    reset = st.button("🔄 Reset results", use_container_width=True)

if reset:
    st.session_state.slide_results = []
    st.rerun()

if run:
    results = []
    progress = st.progress(0, text="Starting…")
    for idx, row in enumerate(selected.itertuples(index=False), start=1):
        progress.progress((idx - 1) / len(selected), text=f"Checking {idx}/{len(selected)} — slide {row.slide_number}")
        result = check_slide_claim(
            claim=row.clean_claim,
            slide_number=row.slide_number,
            slide_title=row.slide_title,
            surrounding_text=row.surrounding_text,
            urls_raw=row.urls,
            api_key=api_key,
            project_context=project_context,
            qa_instruction=qa_instruction,
            model=model,
        )
        results.append({
            "Claim ID": row.claim_id,
            "Slide": row.slide_number,
            "Slide Title": row.slide_title,
            "Element": row.element_name,
            "Claim": row.clean_claim,
            "Raw Text": row.raw_text,
            "URLs": row.urls,
            "Reference Mapping": row.mapping_note,
            "Status": result.get("status", ""),
            "Confidence": result.get("confidence", ""),
            "Verdict": result.get("verdict", ""),
            "Supported Claims": result.get("supported_claims", ""),
            "Unsupported Claims": result.get("unsupported_claims", ""),
            "Unverified Claims": result.get("unverified_claims", ""),
            "Direct Verbatims": result.get("direct_verbatims", ""),
            "Evidence by Source": result.get("evidence_by_source", ""),
            "QA Flags": result.get("qa_flags", ""),
            "Suggested Fix": result.get("suggested_fix", ""),
            "Model": model,
            "sources": result.get("sources", []),
            "usage": result.get("usage", {}),
        })
        time.sleep(0.2)
    progress.progress(1.0, text="Completed")
    st.session_state.slide_results = results

if st.session_state.slide_results:
    results = st.session_state.slide_results
    result_df = pd.DataFrame([{k: v for k, v in r.items() if k not in {"sources", "usage"}} for r in results])
    st.divider()
    st.subheader("3. Review Results")

    counts = result_df["Status"].value_counts()
    metric_cols = st.columns(5)
    metric_cols[0].metric("Total", len(result_df))
    metric_cols[1].metric("Confirmed", int(counts.get("✅ Confirmed", 0)))
    metric_cols[2].metric("Partial", int(counts.get("⚠️ Partial", 0)))
    metric_cols[3].metric("Incorrect", int(counts.get("❌ Incorrect", 0)))
    metric_cols[4].metric("Issues", int(counts.get("❓ Not Found", 0) + counts.get("🔒 Inaccessible", 0)))

    usage_rows = [r.get("usage", {}) for r in results]
    est_cost = sum(float(u.get("estimated_cost_usd") or 0) for u in usage_rows)
    total_tokens = sum(int(u.get("total_tokens") or 0) for u in usage_rows)
    with st.expander("Run details (optional)", expanded=False):
        st.write(f"Claims checked: **{len(result_df)}**")
        st.write(f"API tokens reported: **{total_tokens:,}**")
        st.write(f"Estimated model cost: **US${est_cost:.6f}**")
        st.caption("Operational estimate only. Use the company billing console as the source of truth.")

    st.dataframe(
        result_df[["Slide", "Slide Title", "Claim", "Status", "QA Flags", "Verdict"]],
        hide_index=True,
        use_container_width=True,
    )

    for idx, row in result_df.iterrows():
        with st.expander(f"Slide {row['Slide']} · {row['Status']} · {str(row['Claim'])[:100]}"):
            st.markdown("**Claim**")
            st.write(row["Claim"])
            st.markdown("**Verdict**")
            st.info(row["Verdict"] or "—")
            if row["Supported Claims"]:
                st.markdown("**Supported claims**")
                st.success(row["Supported Claims"])
            if row["Unsupported Claims"]:
                st.markdown("**Unsupported claims**")
                st.error(row["Unsupported Claims"])
            if row.get("Unverified Claims"):
                st.markdown("**Unverified claims (source unavailable)**")
                st.warning(row["Unverified Claims"])
            if row["Direct Verbatims"]:
                st.markdown("**Direct verbatims**")
                st.text(row["Direct Verbatims"])
            if row["Suggested Fix"]:
                st.markdown("**Suggested fix**")
                st.write(row["Suggested Fix"])
            st.markdown("**Source retrieval**")
            source_items = results[idx].get("sources", []) if idx < len(results) else []
            if source_items:
                source_df = pd.DataFrame([{
                    "Source": f"Source {s.get('source_number', '')}",
                    "Retrieval": s.get("retrieval_status", ""),
                    "URL": s.get("url", ""),
                } for s in source_items])
                st.dataframe(source_df, hide_index=True, use_container_width=True)
            else:
                st.caption("No source retrieval metadata available.")
            st.markdown("**References**")
            for url in str(row["URLs"]).split(" | "):
                if url.strip():
                    st.markdown(f"- [{url.strip()}]({url.strip()})")

    try:
        report_bytes = build_report(results)
        st.download_button(
            "⬇️ Download QA workbook (.xlsx)",
            report_bytes,
            file_name="Slide_QA_Review.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            use_container_width=True,
            help="Includes the full review results, source retrieval details, and API usage information for the pilot.",
        )
    except Exception as exc:
        st.error(
            "The review completed, but the Excel workbook could not be generated. "
            "Reset the results and rerun after updating the app files. "
            f"Technical detail: {type(exc).__name__}."
        )
